#!/bin/sh

set -e # Exit immediately if a command exits with a non-zero status.
set -u # Treat unset variables as an error.

# Set location of profile.
echo "--profile"
echo "/config/profile"

# Make sure we don't get ask to be the default browser.
echo "--setDefaultBrowser"

